// <auto-generated />
using System;
using CaseGig.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseGig.Infrastructure.Migrations
{
    [DbContext(typeof(InvestmentDbContext))]
    [Migration("20260501114629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CaseGig.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal>("SaldoDisponivel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            IdCliente = new Guid("11111111-1111-1111-1111-111111111111"),
                            Cpf = "11111111111",
                            Nome = "João Silva",
                            RowVersion = 1L,
                            SaldoDisponivel = 10000.00m
                        },
                        new
                        {
                            IdCliente = new Guid("22222222-2222-2222-2222-222222222222"),
                            Cpf = "22222222222",
                            Nome = "Maria Souza",
                            RowVersion = 1L,
                            SaldoDisponivel = 100.00m
                        });
                });

            modelBuilder.Entity("CaseGig.Domain.Entities.Fundo", b =>
                {
                    b.Property<Guid>("IdFundo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("HorarioCorte")
                        .HasColumnType("time(0)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("StatusCaptacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("ValorCota")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ValorMinimoAporte")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorMinimoPermanencia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFundo");

                    b.ToTable("Fundos");

                    b.HasData(
                        new
                        {
                            IdFundo = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            HorarioCorte = new TimeSpan(0, 14, 0, 0, 0),
                            Nome = "Fundo Renda Fixa",
                            RowVersion = 1L,
                            StatusCaptacao = "ABERTO",
                            ValorCota = 10.00m,
                            ValorMinimoAporte = 100.00m,
                            ValorMinimoPermanencia = 50.00m
                        },
                        new
                        {
                            IdFundo = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            HorarioCorte = new TimeSpan(0, 14, 0, 0, 0),
                            Nome = "Fundo Ações Fechado",
                            RowVersion = 1L,
                            StatusCaptacao = "FECHADO",
                            ValorCota = 20.00m,
                            ValorMinimoAporte = 200.00m,
                            ValorMinimoPermanencia = 100.00m
                        });
                });

            modelBuilder.Entity("CaseGig.Domain.Entities.Ordem", b =>
                {
                    b.Property<Guid>("IdOrdem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataAgendamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdFundo")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("QuantidadeCotas")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdOrdem");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdFundo");

                    b.ToTable("Ordens");
                });

            modelBuilder.Entity("CaseGig.Domain.Entities.Posicao", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdFundo")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("QuantidadeCotas")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("IdCliente", "IdFundo");

                    b.HasIndex("IdFundo");

                    b.ToTable("Posicoes");

                    b.HasData(
                        new
                        {
                            IdCliente = new Guid("11111111-1111-1111-1111-111111111111"),
                            IdFundo = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            QuantidadeCotas = 500m,
                            RowVersion = 1L
                        },
                        new
                        {
                            IdCliente = new Guid("22222222-2222-2222-2222-222222222222"),
                            IdFundo = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            QuantidadeCotas = 5m,
                            RowVersion = 1L
                        });
                });

            modelBuilder.Entity("CaseGig.Domain.Entities.Ordem", b =>
                {
                    b.HasOne("CaseGig.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Ordens")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseGig.Domain.Entities.Fundo", "Fundo")
                        .WithMany("Ordens")
                        .HasForeignKey("IdFundo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Fundo");
                });

            modelBuilder.Entity("CaseGig.Domain.Entities.Posicao", b =>
                {
                    b.HasOne("CaseGig.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Posicoes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseGig.Domain.Entities.Fundo", "Fundo")
                        .WithMany("Posicoes")
                        .HasForeignKey("IdFundo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Fundo");
                });

            modelBuilder.Entity("CaseGig.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Ordens");

                    b.Navigation("Posicoes");
                });

            modelBuilder.Entity("CaseGig.Domain.Entities.Fundo", b =>
                {
                    b.Navigation("Ordens");

                    b.Navigation("Posicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
